apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260615-155148-5wnfybzpfg8e-service
spec:
  selector:
    app: enterprise-system-20260615-155148-5wnfybzpfg8e
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
